# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10IAlVB6adjmX1TFNhkRh1Eq2zAFi5bvA
"""

import streamlit as st
import random

st.set_page_config(layout="wide")
st.title('Test Streamlit V2')
st.write('Hello World!')

col1_1, col1_2 = st.column(2)
with col1_1:
    st.header("AAAAAA")
    with col1_2:
    st.header("BBBBBB")

col2_1, col2_2 = st.column([3, 1], border=True)
col2_1.header("CCCCCC")
col2_2.header("DDDDDD")

if st.button('Generate Random Number'):
    random_number = random.randint(1, 100)
    st.write(f'Random Number: {random_number}')