# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10IAlVB6adjmX1TFNhkRh1Eq2zAFi5bvA
"""

import streamlit as st
import random

st.title('Test Streamlit V2')
st.write('Hello World!')

if st.button('Generate Random Number'):
    random_number = random.randint(1, 100)
    st.write(f'Random Number: {random_number}')